//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeagueOfNinja.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EquipmentStatistic
    {
        public int EquitmentId { get; set; }
        public string StatisticType { get; set; }
        public int StatisticValue { get; set; }
    
        public virtual Equipment Equipment { get; set; }
        public virtual TypOfStatistic TypOfStatistic { get; set; }
    }
}
